// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqOqcNCyIMUojqWBD3On7A1yIxFBU20bo',
    appId: '1:276793636798:web:97eb604fd1e60ca9d0abef',
    messagingSenderId: '276793636798',
    projectId: 'collegemessapp',
    authDomain: 'collegemessapp.firebaseapp.com',
    storageBucket: 'collegemessapp.firebasestorage.app',
    measurementId: 'G-1RLVGZ60P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGHpny52CnQdvqIe1vL3hWHoh_dZ_e9d0',
    appId: '1:276793636798:android:58d4f17389d18148d0abef',
    messagingSenderId: '276793636798',
    projectId: 'collegemessapp',
    storageBucket: 'collegemessapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO44pCjDNLrnAf73dA58udu5g6ccg7z8g',
    appId: '1:276793636798:ios:5b7c505c17651df8d0abef',
    messagingSenderId: '276793636798',
    projectId: 'collegemessapp',
    storageBucket: 'collegemessapp.firebasestorage.app',
    iosBundleId: 'com.example.messApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO44pCjDNLrnAf73dA58udu5g6ccg7z8g',
    appId: '1:276793636798:ios:5b7c505c17651df8d0abef',
    messagingSenderId: '276793636798',
    projectId: 'collegemessapp',
    storageBucket: 'collegemessapp.firebasestorage.app',
    iosBundleId: 'com.example.messApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqOqcNCyIMUojqWBD3On7A1yIxFBU20bo',
    appId: '1:276793636798:web:a62ec15e6f590abcd0abef',
    messagingSenderId: '276793636798',
    projectId: 'collegemessapp',
    authDomain: 'collegemessapp.firebaseapp.com',
    storageBucket: 'collegemessapp.firebasestorage.app',
    measurementId: 'G-FQG2P7BYX1',
  );
}
