import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by `flutterfire configure`

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final Future<FirebaseApp> _initialization = Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Firebase Connection Status',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: FutureBuilder(
        future: _initialization,
        builder: (context, snapshot) {
          // Show loading indicator while connecting
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              body: Center(child: CircularProgressIndicator()),
            );
          }

          // Show error if connection fails
          if (snapshot.hasError) {
            return const Scaffold(
              body: Center(
                child: Text(
                  '❌ Failed to connect to Firebase',
                  style: TextStyle(fontSize: 20, color: Colors.red),
                ),
              ),
            );
          }

          // Show success if connected
          return const Scaffold(
            body: Center(
              child: Text(
                '✅ Connected to backend Firebase',
                style: TextStyle(fontSize: 20, color: Colors.green),
              ),
            ),
          );
        },
      ),
    );
  }
}

